version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ checksum "yarn.lock" }}
      - run:
          name: "📦 install"
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: node-{{ checksum "yarn.lock" }}
      - run:
          name: "👮🏻‍♂️ lint"
          command: "./ci/lint.sh"
      - run:
          name: "🛠 build"
          command: "./ci/build.sh"
      - run:
          name: "🏗 provision"
          command: "./ci/provision.sh $environment"
      - run:
          name: "🚀 deploy"
          command: "./ci/deploy.sh $environment"
